#!/bin/bash
# Post-processing merges for experiments D and E.
#
# Companion to run_postprocess_chain.sh, which covers B (merge) and C (LLM
# re-run + merge).  This one is launched only AFTER both the monitored chain
# and the B/C post-process chain have finished, so the three never contend for
# the single vLLM instance.
#
# Usage:  bash ./run_postprocess_chain2.sh            # wait, then merge D + E
#         WAIT=0 bash ./run_postprocess_chain2.sh     # merge now, no waiting
#
# NOTE: do not edit this file while it is running - bash reads scripts by byte
# offset.  Write a new file instead.
set -uo pipefail

cd /202131510121/lyt/aiops_diagnosis

PY=/202131510121/conda/envs/micro/bin/python
LOG_DIR=outputs_experiment_chain_monitored
CHAIN_LOG="$LOG_DIR/chain.log"
POST_LOG="$LOG_DIR/postprocess_chain.log"
LOG="$LOG_DIR/postprocess_chain2.log"
WAIT="${WAIT:-1}"
POLL="${POLL:-120}"
mkdir -p "$LOG_DIR"

log() { echo "$(date -Is) [postproc2] $*" | tee -a "$LOG"; }

D_DIR=outputs_experiment_d_llm
E_DIR=outputs_experiment_e_llm

# ------------------------------------------------------------------ helpers

count_lines() {
    [ -f "$1" ] || { echo 0; return; }
    wc -l < "$1" 2>/dev/null || echo 0
}

# 两个前置条件都满足才动手：
#   1) 主链跑完 e_llm
#   2) B/C 后处理链（含 C 的合并）跑完
wait_for_prereqs() {
    log "等待前置条件：主链 e_llm + B/C 后处理链 ..."
    while true; do
        local ok_chain=0 ok_post=0
        grep -q "DONE e_llm" "$CHAIN_LOG" 2>/dev/null && ok_chain=1
        grep -q "POSTPROCESS CHAIN COMPLETE" "$POST_LOG" 2>/dev/null && ok_post=1

        if [ "$ok_chain" = "1" ] && [ "$ok_post" = "1" ]; then
            log "前置条件已满足（e_llm 完成 + B/C 后处理完成）"
            return 0
        fi

        # 进程已经全部退出但标记仍未出现 -> 说明有阶段失败，交人工判断
        if ! pgrep -f "run_chain_monitored.sh" >/dev/null 2>&1 \
           && ! pgrep -f "run_postprocess_chain.sh" >/dev/null 2>&1; then
            log "!! 两个链进程都已不在运行，但标记不全（e_llm=$ok_chain post=$ok_post）"
            log "   可能有阶段失败，请人工确认；WAIT=0 可跳过等待直接合并"
            return 1
        fi
        sleep "$POLL"
    done
}

merge_one() {
    # NOTE: bash word-expands every argument of `local` before assigning any of
    # them, so `local dir="$2" src="$dir/..."` dies with `dir: unbound variable`
    # under `set -u`.  Keep these as separate statements.
    local name="$1"
    local dir="$2"
    local src
    local out
    local n
    src="$dir/predictions_high_conf.jsonl"
    out="$dir/predictions_high_conf.merged.jsonl"
    n=$(count_lines "$src")
    if [ "$n" -eq 0 ]; then
        log "--- $name 跳过：$src 为空或不存在 ---"
        return 3
    fi
    log "--- $name 合并开始（输入 $n 条）---"
    "$PY" -u merge_predictions_llm.py "$src" \
        --gap-minutes 20 --max-span-minutes 60 --workers 8 \
        --max-tokens 0 --llm-timeout 1800 \
        --out "$out" \
        > "$dir/merge_llm.log" 2>&1
    local rc=$?
    log "--- $name 合并 rc=$rc ---"
    tail -6 "$dir/merge_llm.log" 2>/dev/null | sed 's/^/    /' | tee -a "$LOG"
    return $rc
}

# ------------------------------------------------------------------ main

log "===== POSTPROCESS CHAIN 2 START (D + E) ====="

if [ "$WAIT" = "1" ]; then
    wait_for_prereqs || exit 2
fi

merge_one "D" "$D_DIR"; d_rc=$?
merge_one "E" "$E_DIR"; e_rc=$?

log "===== POSTPROCESS CHAIN 2 COMPLETE (d=$d_rc e=$e_rc) ====="

log "--- 产物条数汇总 ---"
for d in outputs_experiment_b_incident_llm outputs_experiment_c_full_llm \
         outputs_experiment_d_llm outputs_experiment_e_llm; do
    printf "    %-38s raw=%-6s dedup=%-6s merged=%-6s\n" \
        "$d" \
        "$(count_lines "$d/predictions_high_conf.jsonl")" \
        "$(count_lines "$d/predictions_high_conf.dedup.jsonl")" \
        "$(count_lines "$d/predictions_high_conf.merged.jsonl")" | tee -a "$LOG"
done
